In [1]:
import efinance as ef
# 股票代码
stock_code = 'AAPL'
data = ef.stock.get_quote_history(stock_code)
print(data)

     股票名称  股票代码          日期      开盘      收盘      最高      最低       成交量  \
0      苹果  AAPL  1984-09-07   -7.19   -7.19   -7.18   -7.19   2981600
1      苹果  AAPL  1984-09-10   -7.19   -7.19   -7.18   -7.19   2346400
2      苹果  AAPL  1984-09-11   -7.18   -7.18   -7.18   -7.18   5444000
3      苹果  AAPL  1984-09-12   -7.18   -7.19   -7.18   -7.19   4773600
4      苹果  AAPL  1984-09-13   -7.18   -7.18   -7.18   -7.18   7429600
...   ...   ...         ...     ...     ...     ...     ...       ...
9236   苹果  AAPL  2023-07-14  190.23  190.69  191.18  189.63  41616242
9237   苹果  AAPL  2023-07-17  191.90  193.99  194.32  191.81  50520159
9238   苹果  AAPL  2023-07-18  193.35  193.73  194.33  192.42  48353774
9239   苹果  AAPL  2023-07-19  193.10  195.10  198.23  192.65  80507323
9240   苹果  AAPL  2023-07-20  195.09  193.13  196.47  192.50  59581196

               成交额    振幅   涨跌幅   涨跌额   换手率
0     0.000000e+00  0.00  0.00  0.00  0.02
1     0.000000e+00 -0.14  0.00  0.00  0.01
2     0.000000e+00  0.00  0.14  0.01  0.03
3     0.000000e+00 -0.14 -0.14 -0.01  0.03
4     0.000000e+00  0.00  0.14  0.01  0.05
...            ...   ...   ...   ...   ...
9236  7.926280e+09  0.81  0.08  0.15  0.26
9237  9.766868e+09  1.32  1.73  3.30  0.32
9238  9.350451e+09  0.98 -0.13 -0.26  0.31
9239  1.569778e+10  2.88  0.71  1.37  0.51
9240  1.157642e+10  2.03 -1.01 -1.97  0.38

[9241 rows x 13 columns]

In [2]:
type(data)

pandas.core.frame.DataFrame

In [18]:
data = ef.stock.get_quote_history('BAC',beg='20060101')
print(data)

      股票名称 股票代码          日期     开盘     收盘     最高     最低       成交量  \
0     美国银行  BAC  2007-03-19  40.56  41.13  41.15  40.11  12994400
1     美国银行  BAC  2007-03-20  41.13  41.52  41.59  41.07  10062100
2     美国银行  BAC  2007-03-21  41.54  42.62  42.76  41.34  21718660
3     美国银行  BAC  2007-03-22  42.74  42.40  42.90  42.17  21557600
4     美国银行  BAC  2007-03-23  42.46  42.45  42.76  42.17  13102799
...    ...  ...         ...    ...    ...    ...    ...       ...
4108  美国银行  BAC  2023-07-14  30.00  29.11  30.10  29.05  58720333
4109  美国银行  BAC  2023-07-17  29.15  29.40  29.56  29.12  49477157
4110  美国银行  BAC  2023-07-18  30.00  30.70  30.86  29.92  98253845
4111  美国银行  BAC  2023-07-19  30.89  31.53  31.70  30.69  70619789
4112  美国银行  BAC  2023-07-20  31.33  31.69  31.80  31.26  42128768

               成交额    振幅    涨跌幅   涨跌额   换手率
0     0.000000e+00  3.14  24.00  7.96  0.29
1     0.000000e+00  1.26   0.95  0.39  0.23
2     0.000000e+00  3.42   2.65  1.10  0.49
3     0.000000e+00  1.71  -0.52 -0.22  0.48
4     0.000000e+00  1.39   0.12  0.05  0.29
...            ...   ...    ...   ...   ...
4108  1.722606e+09  3.54  -1.89 -0.56  0.74
4109  1.455203e+09  1.51   1.00  0.29  0.62
4110  3.002014e+09  3.20   4.42  1.30  1.24
4111  2.215753e+09  3.29   2.70  0.83  0.89
4112  1.331290e+09  1.71   0.51  0.16  0.53

[4113 rows x 13 columns]

In [14]:
print(data)

      股票名称 股票代码          日期     开盘     收盘     最高     最低       成交量  \
0     美国银行  BAC  2007-03-19  40.56  41.13  41.15  40.11  12994400
1     美国银行  BAC  2007-03-20  41.13  41.52  41.59  41.07  10062100
2     美国银行  BAC  2007-03-21  41.54  42.62  42.76  41.34  21718660
3     美国银行  BAC  2007-03-22  42.74  42.40  42.90  42.17  21557600
4     美国银行  BAC  2007-03-23  42.46  42.45  42.76  42.17  13102799
...    ...  ...         ...    ...    ...    ...    ...       ...
4108  美国银行  BAC  2023-07-14  30.00  29.11  30.10  29.05  58720333
4109  美国银行  BAC  2023-07-17  29.15  29.40  29.56  29.12  49477157
4110  美国银行  BAC  2023-07-18  30.00  30.70  30.86  29.92  98253845
4111  美国银行  BAC  2023-07-19  30.89  31.53  31.70  30.69  70619789
4112  美国银行  BAC  2023-07-20  31.33  31.69  31.80  31.26  42128768

               成交额    振幅    涨跌幅   涨跌额   换手率
0     0.000000e+00  3.14  24.00  7.96  0.29
1     0.000000e+00  1.26   0.95  0.39  0.23
2     0.000000e+00  3.42   2.65  1.10  0.49
3     0.000000e+00  1.71  -0.52 -0.22  0.48
4     0.000000e+00  1.39   0.12  0.05  0.29
...            ...   ...    ...   ...   ...
4108  1.722606e+09  3.54  -1.89 -0.56  0.74
4109  1.455203e+09  1.51   1.00  0.29  0.62
4110  3.002014e+09  3.20   4.42  1.30  1.24
4111  2.215753e+09  3.29   2.70  0.83  0.89
4112  1.331290e+09  1.71   0.51  0.16  0.53

[4113 rows x 13 columns]

In [12]:
print(data)

     股票名称  股票代码          日期      开盘      收盘      最高      最低       成交量  \
0      苹果  AAPL  2007-03-19   -4.05   -4.02   -4.00   -4.07  25471457
1      苹果  AAPL  2007-03-20   -4.01   -4.00   -3.99   -4.02  17474064
2      苹果  AAPL  2007-03-21   -3.98   -3.92   -3.91   -4.00  24551703
3      苹果  AAPL  2007-03-22   -3.92   -3.91   -3.90   -3.95  20188862
4      苹果  AAPL  2007-03-23   -3.94   -3.93   -3.91   -3.94  16119797
...   ...   ...         ...     ...     ...     ...     ...       ...
4108   苹果  AAPL  2023-07-14  190.23  190.69  191.18  189.63  41616242
4109   苹果  AAPL  2023-07-17  191.90  193.99  194.32  191.81  50520159
4110   苹果  AAPL  2023-07-18  193.35  193.73  194.33  192.42  48353774
4111   苹果  AAPL  2023-07-19  193.10  195.10  198.23  192.65  80507323
4112   苹果  AAPL  2023-07-20  195.09  193.13  196.47  192.50  59581196

               成交额    振幅    涨跌幅   涨跌额   换手率
0     0.000000e+00 -1.05  39.91  2.67  2.96
1     0.000000e+00 -0.75   0.50  0.02  2.02
2     0.000000e+00 -2.25   2.00  0.08  2.84
3     0.000000e+00 -1.28   0.26  0.01  2.34
4     0.000000e+00 -0.77  -0.51 -0.02  1.86
...            ...   ...    ...   ...   ...
4108  7.926280e+09  0.81   0.08  0.15  0.26
4109  9.766868e+09  1.32   1.73  3.30  0.32
4110  9.350451e+09  0.98  -0.13 -0.26  0.31
4111  1.569778e+10  2.88   0.71  1.37  0.51
4112  1.157642e+10  2.03  -1.01 -1.97  0.38

[4113 rows x 13 columns]

In [10]:
print(data)

     股票名称  股票代码          日期      开盘      收盘      最高      最低       成交量  \
0      苹果  AAPL  1984-09-07   -7.19   -7.19   -7.18   -7.19   2981600
1      苹果  AAPL  1984-09-10   -7.19   -7.19   -7.18   -7.19   2346400
2      苹果  AAPL  1984-09-11   -7.18   -7.18   -7.18   -7.18   5444000
3      苹果  AAPL  1984-09-12   -7.18   -7.19   -7.18   -7.19   4773600
4      苹果  AAPL  1984-09-13   -7.18   -7.18   -7.18   -7.18   7429600
...   ...   ...         ...     ...     ...     ...     ...       ...
9236   苹果  AAPL  2023-07-14  190.23  190.69  191.18  189.63  41616242
9237   苹果  AAPL  2023-07-17  191.90  193.99  194.32  191.81  50520159
9238   苹果  AAPL  2023-07-18  193.35  193.73  194.33  192.42  48353774
9239   苹果  AAPL  2023-07-19  193.10  195.10  198.23  192.65  80507323
9240   苹果  AAPL  2023-07-20  195.09  193.13  196.47  192.50  59581196

               成交额    振幅   涨跌幅   涨跌额   换手率
0     0.000000e+00  0.00  0.00  0.00  0.02
1     0.000000e+00 -0.14  0.00  0.00  0.01
2     0.000000e+00  0.00  0.14  0.01  0.03
3     0.000000e+00 -0.14 -0.14 -0.01  0.03
4     0.000000e+00  0.00  0.14  0.01  0.05
...            ...   ...   ...   ...   ...
9236  7.926280e+09  0.81  0.08  0.15  0.26
9237  9.766868e+09  1.32  1.73  3.30  0.32
9238  9.350451e+09  0.98 -0.13 -0.26  0.31
9239  1.569778e+10  2.88  0.71  1.37  0.51
9240  1.157642e+10  2.03 -1.01 -1.97  0.38

[9241 rows x 13 columns]

In [19]:
import efinance as ef

In [20]:
ef.stock.get_realtime_quotes()

,股票代码,股票名称,涨跌幅,最新价,最高,最低,今开,涨跌额,换手率,量比,动态市盈率,成交量,成交额,昨日收盘,总市值,流通市值,行情ID,市场类型,更新时间,最新交易日
0,301499,N维科精,80.92,35.28,42.08,35.2,40.0,15.78,73.72,-,124.63,241677,938921695.71,19.5,4877631672,1156540987,0.301499,深A,2023-07-21 15:34:39,2023-07-21
1,301281,科源制药,20.01,31.97,31.97,26.4,26.5,5.33,34.21,7.71,26.97,87881,271064989.73,26.64,3462031300,821346417,0.301281,深A,2023-07-21 15:35:00,2023-07-21
2,300898,熊猫乳品,16.9,29.6,30.3,25.52,25.52,4.28,41.98,4.91,48.33,223235,628024324.48,25.32,3704884000,1574185010,0.300898,深A,2023-07-21 15:34:12,2023-07-21
3,300601,康泰生物,14.54,28.6,29.56,26.47,26.8,3.63,4.86,6.98,38.87,428302,1196393610.99,24.97,31943695555,25207336554,0.300601,深A,2023-07-21 15:34:27,2023-07-21
4,301505,C苏州规,14.26,42.47,46.25,35.33,36.0,5.3,75.14,1.13,239.67,148151,592255564.67,37.17,3737360000,837321150,0.301505,深A,2023-07-21 15:34:33,2023-07-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5473,300503,昊志机电,-16.55,16.39,18.93,16.13,18.68,-3.25,28.43,1.31,-102.4,618729,1070054815.16,19.64,5016533782,3567496898,0.300503,深A,2023-07-21 15:34:54,2023-07-21
5474,301007,德迈仕,-16.69,16.27,18.88,16.27,18.85,-3.26,32.33,1.34,78.97,399647,680779265.94,19.53,2494841800,2011098093,0.301007,深A,2023-07-21 15:34:36,2023-07-21
5475,301398,星源卓镁,-17.54,60.8,78.26,60.68,69.0,-12.93,59.97,0.96,71.78,115579,818742879.04,73.73,4864000000,1171813965,0.301398,深A,2023-07-21 15:34:48,2023-07-21
5476,301338,凯格精机,-17.63,50.05,58.3,50.0,54.0,-10.71,62.33,1.67,115.33,154142,828759578.71,60.76,5325320000,1237674238,0.301338,深A,2023-07-21 15:34:30,2023-07-21
5477,301255,通力科技,-19.99,53.14,62.44,53.14,61.34,-13.28,54.34,1.46,83.12,147817,855776434.2,66.42,5781632000,1445408000,0.301255,深A,2023-07-21 15:34:42,2023-07-21

In [33]:
from efinance.utils import search_quote
search_quote(keyword='DJI',count=10)

[Quote(code='DJIA', name='Global X Dow 30 Covered Call ET', pinyin='GLOBALXDOW30COVEREDCALLET', id='DJIA7', jys='AMEX', classify='UsStock', market_type='7', security_typeName='美股', security_type='7', mkt_num='107', type_us='5', quote_id='107.DJIA', unified_code='DJIA', inner_code='13868919752883'),
 Quote(code='DJIA', name='道琼斯', pinyin='DQS', id='DJIA_UI', jys='QQZS', classify='UniversalIndex', market_type='_UI', security_typeName='指数', security_type='11', mkt_num='100', type_us='0', quote_id='100.DJIA', unified_code='DJIA', inner_code='20933916664720'),
 Quote(code='DOGG', name='FT Cboe Vest DJIA Dogs 10 Targe', pinyin='FTCBOEVESTDJIADOGS10TARGE', id='DOGG7', jys='AMEX', classify='UsStock', market_type='7', security_typeName='美股', security_type='7', mkt_num='107', type_us='5', quote_id='107.DOGG', unified_code='DOGG', inner_code='48969702947325'),
 Quote(code='NDJI', name='Nationwide Dow Jones Risk-Manag', pinyin='NATIONWIDEDOWJONESRISKMANAG', id='NDJI7', jys='AMEX', classify='UsStock', market_type='7', security_typeName='美股', security_type='7', mkt_num='107', type_us='5', quote_id='107.NDJI', unified_code='NDJI', inner_code='44826000527811'),
 Quote(code='0OO5', name='ELEKTROMETAL AD-PAZARDJIK ORD S', pinyin='ELEKTROMETALADPAZARDJIKORDS', id='0OO5_UKS', jys='LSE', classify='LSE', market_type='_UKS', security_typeName='英股', security_type='24', mkt_num='155', type_us='1', quote_id='155.0OO5', unified_code='0OO5', inner_code='15748546078427'),
 Quote(code='47BH', name='HSBC BANK PLC WRT LKD JIANGU TR', pinyin='HSBCBANKPLCWRTLKDJIANGUTR', id='47BH_UKS', jys='LSE', classify='LSE', market_type='_UKS', security_typeName='债券', security_type='16', mkt_num='155', type_us='4', quote_id='155.47BH', unified_code='47BH', inner_code='20063626059131'),
 Quote(code='74CQ', name='HSBC BANK PLC WNTS LKD ORD JIND', pinyin='HSBCBANKPLCWNTSLKDORDJIND', id='74CQ_UKS', jys='LSE', classify='LSE', market_type='_UKS', security_typeName='债券', security_type='16', mkt_num='155', type_us='4', quote_id='155.74CQ', unified_code='74CQ', inner_code='22620347640411'),
 Quote(code='IGDA', name='INVESCO MARKETS II PLC IVZ DJ I', pinyin='INVESCOMARKETSIIPLCIVZDJI', id='IGDA_UKS', jys='LSE', classify='LSE', market_type='_UKS', security_typeName='英股', security_type='24', mkt_num='155', type_us='3', quote_id='155.IGDA', unified_code='IGDA', inner_code='29251133247941')]

In [41]:
from efinance.common import get_latest_quote
ef.common.get_quote_history('100.DJIA')

证券代码 "100.DJIA" 可能有误

Empty DataFrame
Columns: [名称, 代码, 日期, 开盘, 收盘, 最高, 最低, 成交量, 成交额, 振幅, 涨跌幅, 涨跌额, 换手率]
Index: []

In [3]:
ef.stock.get_members('000300')

       指数代码   指数名称    股票代码  股票名称  股票权重
0    000300  沪深300  600519  贵州茅台  6.04
1    000300  沪深300  300750  宁德时代  3.19
2    000300  沪深300  601318  中国平安  2.85
3    000300  沪深300  600036  招商银行  2.16
4    000300  沪深300  000858   五粮液  1.77
..      ...    ...     ...   ...   ...
295  000300  沪深300  601236  红塔证券  0.04
296  000300  沪深300  000800  一汽解放  0.04
297  000300  沪深300  605499  东鹏饮料  0.04
298  000300  沪深300  300979  华利集团  0.04
299  000300  沪深300  001289  龙源电力  0.02

[300 rows x 5 columns]

In [2]:
import efinance as ef

In [4]:
ef.stock.get_members('000300')

       指数代码   指数名称    股票代码  股票名称  股票权重
0    000300  沪深300  600519  贵州茅台  6.04
1    000300  沪深300  300750  宁德时代  3.19
2    000300  沪深300  601318  中国平安  2.85
3    000300  沪深300  600036  招商银行  2.16
4    000300  沪深300  000858   五粮液  1.77
..      ...    ...     ...   ...   ...
295  000300  沪深300  601236  红塔证券  0.04
296  000300  沪深300  000800  一汽解放  0.04
297  000300  沪深300  605499  东鹏饮料  0.04
298  000300  沪深300  300979  华利集团  0.04
299  000300  沪深300  001289  龙源电力  0.02

[300 rows x 5 columns]

In [5]:
data300 = ef.stock.get_members('000300')

In [6]:
data300.to_csv('list300')