In [55]:
import efinance as ef
# 股票代码
stock_code = 'AAPL'
data = ef.stock.get_quote_history(stock_code)
print(data)

     股票名称  股票代码          日期      开盘      收盘      最高      最低       成交量  \
0      苹果  AAPL  1984-09-07   -7.43   -7.43   -7.42   -7.43   2981600
1      苹果  AAPL  1984-09-10   -7.43   -7.43   -7.42   -7.43   2346400
2      苹果  AAPL  1984-09-11   -7.42   -7.42   -7.42   -7.42   5444000
3      苹果  AAPL  1984-09-12   -7.42   -7.43   -7.42   -7.43   4773600
4      苹果  AAPL  1984-09-13   -7.42   -7.42   -7.42   -7.42   7429600
...   ...   ...         ...     ...     ...     ...     ...       ...
9267   苹果  AAPL  2023-08-28  180.09  180.19  180.59  178.55  43820697
9268   苹果  AAPL  2023-08-29  179.70  184.12  184.90  179.50  53003948
9269   苹果  AAPL  2023-08-30  184.94  187.65  187.85  184.74  60813888
9270   苹果  AAPL  2023-08-31  187.84  187.87  189.12  187.48  60794467
9271   苹果  AAPL  2023-09-01  189.57  188.43  189.92  188.28  14944940

               成交额    振幅   涨跌幅   涨跌额   换手率
0     0.000000e+00  0.00  0.00  0.00  0.02
1     0.000000e+00 -0.13  0.00  0.00  0.02
2     0.000000e+00  0.00  0.13  0.01  0.03
3     0.000000e+00 -0.13 -0.13 -0.01  0.03
4     0.000000e+00  0.00  0.13  0.01  0.05
...            ...   ...   ...   ...   ...
9267  7.871021e+09  1.14  0.88  1.58  0.28
9268  9.714757e+09  3.00  2.18  3.93  0.34
9269  1.136908e+10  1.69  1.92  3.53  0.39
9270  1.144061e+10  0.87  0.12  0.22  0.39
9271  2.824095e+09  0.87  0.30  0.56  0.10

[9272 rows x 13 columns]

In [56]:
type(data)

pandas.core.frame.DataFrame

In [57]:
data = ef.stock.get_quote_history('BAC',beg='20060101')
print(data)

      股票名称 股票代码          日期     开盘     收盘     最高     最低       成交量  \
0     美国银行  BAC  2007-03-19  40.32  40.89  40.91  39.87  12994400
1     美国银行  BAC  2007-03-20  40.89  41.28  41.35  40.83  10062100
2     美国银行  BAC  2007-03-21  41.30  42.38  42.52  41.10  21718660
3     美国银行  BAC  2007-03-22  42.50  42.16  42.66  41.93  21557600
4     美国银行  BAC  2007-03-23  42.22  42.21  42.52  41.93  13102799
...    ...  ...         ...    ...    ...    ...    ...       ...
4139  美国银行  BAC  2023-08-28  28.45  28.52  28.76  28.33  33075190
4140  美国银行  BAC  2023-08-29  28.65  28.93  29.02  28.48  30428198
4141  美国银行  BAC  2023-08-30  28.98  28.80  29.03  28.69  33366353
4142  美国银行  BAC  2023-08-31  28.93  28.67  28.97  28.53  37242989
4143  美国银行  BAC  2023-09-01  28.75  28.98  29.13  28.75   9731199

               成交额    振幅    涨跌幅   涨跌额   换手率
0     0.000000e+00  3.16  24.17  7.96  0.29
1     0.000000e+00  1.27   0.95  0.39  0.23
2     0.000000e+00  3.44   2.66  1.10  0.49
3     0.000000e+00  1.72  -0.52 -0.22  0.48
4     0.000000e+00  1.40   0.12  0.05  0.29
...            ...   ...    ...   ...   ...
4139  9.527991e+08  1.52   0.92  0.26  0.42
4140  8.850975e+08  1.89   1.44  0.41  0.38
4141  9.697807e+08  1.18  -0.45 -0.13  0.42
4142  1.069109e+09  1.53  -0.45 -0.13  0.47
4143  2.824080e+08  1.33   1.08  0.31  0.12

[4144 rows x 13 columns]

In [58]:
import efinance as ef

In [59]:
ef.stock.get_realtime_quotes()

,股票代码,股票名称,涨跌幅,最新价,最高,最低,今开,涨跌额,换手率,量比,动态市盈率,成交量,成交额,昨日收盘,总市值,流通市值,行情ID,市场类型,更新时间,最新交易日
0,603270,N金帝,121.73,48.27,61.0,36.5,39.9,26.5,85.01,-,58.77,416864,1877425208.0,21.77,10576278816,2367137775,1.603270,沪A,2023-09-01 15:59:45,2023-09-01
1,870976,N视声,23.4,12.71,14.27,10.99,11.0,2.41,78.72,906.47,20.05,139959,182754708.08,10.3,644155510,225971090,0.870976,深A,2023-09-01 15:32:51,2023-09-01
2,300050,世纪鼎利,20.05,5.03,5.03,4.13,4.19,0.84,11.59,4.6,-205.69,631179,297261251.73,4.19,2740578992,2738906672,0.300050,深A,2023-09-01 15:34:45,2023-09-01
3,300106,西部牧业,20.04,11.62,11.62,9.68,9.75,1.94,15.37,2.26,396.32,324754,361411628.06,9.68,2455681442,2455681442,0.300106,深A,2023-09-01 15:34:48,2023-09-01
4,301320,豪江智能,19.98,25.34,25.34,21.08,21.08,4.22,23.94,1.76,80.48,102859,256323454.32,21.12,4591608000,1088725675,0.301320,深A,2023-09-01 15:34:09,2023-09-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5506,688671,碧兴物联,-13.03,67.99,77.55,66.68,76.0,-10.19,59.50,0.87,111.65,98837,717283756.0,78.18,5338500011,1129369788,1.688671,沪A,2023-09-01 15:59:55,2023-09-01
5507,301281,科源制药,-14.37,44.14,48.16,44.02,47.42,-7.41,48.70,1.4,46.67,125117,575087284.58,51.55,4779920600,1134007847,0.301281,深A,2023-09-01 15:34:33,2023-09-01
5508,688651,盛邦安全,-14.6,67.16,85.0,66.05,83.0,-11.48,65.93,2.56,-401.6,104019,776603599.0,78.64,5063796840,1059532749,1.688651,沪A,2023-09-01 15:59:47,2023-09-01
5509,300169,天晟新材,-15.82,8.3,10.05,8.3,9.95,-1.56,33.42,0.84,-62.97,1008348,917250103.42,9.86,2705670022,2504406991,0.300169,深A,2023-09-01 15:34:42,2023-09-01
5510,688591,泰凌微,-16.48,36.75,44.46,36.5,44.29,-7.25,57.25,0.86,154.12,297949,1191719839.0,44.0,8820000000,1912659924,1.688591,沪A,2023-09-01 15:59:53,2023-09-01

In [60]:
from efinance.utils import search_quote
search_quote(keyword='DJI',count=10)

[Quote(code='DJIA', name='Global X Dow 30 Covered Call ET', pinyin='GLOBALXDOW30COVEREDCALLET', id='DJIA7', jys='AMEX', classify='UsStock', market_type='7', security_typeName='美股', security_type='7', mkt_num='107', type_us='5', quote_id='107.DJIA', unified_code='DJIA', inner_code='13868919752883'),
 Quote(code='DJIA', name='道琼斯', pinyin='DQS', id='DJIA_UI', jys='QQZS', classify='UniversalIndex', market_type='_UI', security_typeName='指数', security_type='11', mkt_num='100', type_us='0', quote_id='100.DJIA', unified_code='DJIA', inner_code='20933916664720'),
 Quote(code='DOGG', name='FT Cboe Vest DJIA Dogs 10 Targe', pinyin='FTCBOEVESTDJIADOGS10TARGE', id='DOGG7', jys='AMEX', classify='UsStock', market_type='7', security_typeName='美股', security_type='7', mkt_num='107', type_us='5', quote_id='107.DOGG', unified_code='DOGG', inner_code='48969702947325'),
 Quote(code='NDJI', name='Nationwide Dow Jones Risk-Manag', pinyin='NATIONWIDEDOWJONESRISKMANAG', id='NDJI7', jys='AMEX', classify='UsStock', market_type='7', security_typeName='美股', security_type='7', mkt_num='107', type_us='5', quote_id='107.NDJI', unified_code='NDJI', inner_code='44826000527811'),
 Quote(code='0OO5', name='ELEKTROMETAL AD-PAZARDJIK ORD S', pinyin='ELEKTROMETALADPAZARDJIKORDS', id='0OO5_UKS', jys='LSE', classify='LSE', market_type='_UKS', security_typeName='英股', security_type='24', mkt_num='155', type_us='1', quote_id='155.0OO5', unified_code='0OO5', inner_code='15748546078427'),
 Quote(code='47BH', name='HSBC BANK PLC WRT LKD JIANGU TR', pinyin='HSBCBANKPLCWRTLKDJIANGUTR', id='47BH_UKS', jys='LSE', classify='LSE', market_type='_UKS', security_typeName='债券', security_type='16', mkt_num='155', type_us='4', quote_id='155.47BH', unified_code='47BH', inner_code='20063626059131'),
 Quote(code='74CQ', name='HSBC BANK PLC WNTS LKD ORD JIND', pinyin='HSBCBANKPLCWNTSLKDORDJIND', id='74CQ_UKS', jys='LSE', classify='LSE', market_type='_UKS', security_typeName='债券', security_type='16', mkt_num='155', type_us='4', quote_id='155.74CQ', unified_code='74CQ', inner_code='22620347640411'),
 Quote(code='IGDA', name='INVESCO MARKETS II PLC IVZ DJ I', pinyin='INVESCOMARKETSIIPLCIVZDJI', id='IGDA_UKS', jys='LSE', classify='LSE', market_type='_UKS', security_typeName='英股', security_type='24', mkt_num='155', type_us='3', quote_id='155.IGDA', unified_code='IGDA', inner_code='29251133247941')]

In [61]:
from efinance.common import get_latest_quote
ef.common.get_quote_history('100.DJIA')

证券代码 "100.DJIA" 可能有误

Empty DataFrame
Columns: [名称, 代码, 日期, 开盘, 收盘, 最高, 最低, 成交量, 成交额, 振幅, 涨跌幅, 涨跌额, 换手率]
Index: []

In [62]:
ef.stock.get_members('000300')

       指数代码   指数名称    股票代码  股票名称  股票权重
0    000300  沪深300  600519  贵州茅台  6.25
1    000300  沪深300  300750  宁德时代  3.36
2    000300  沪深300  601318  中国平安  2.80
3    000300  沪深300  600036  招商银行  2.10
4    000300  沪深300  000858   五粮液  1.64
..      ...    ...     ...   ...   ...
295  000300  沪深300  601698  中国卫通  0.04
296  000300  沪深300  300979  华利集团  0.04
297  000300  沪深300  000800  一汽解放  0.04
298  000300  沪深300  601236  红塔证券  0.04
299  000300  沪深300  001289  龙源电力  0.02

[300 rows x 5 columns]

In [63]:
import efinance as ef

In [64]:
ef.stock.get_members('000300')

       指数代码   指数名称    股票代码  股票名称  股票权重
0    000300  沪深300  600519  贵州茅台  6.25
1    000300  沪深300  300750  宁德时代  3.36
2    000300  沪深300  601318  中国平安  2.80
3    000300  沪深300  600036  招商银行  2.10
4    000300  沪深300  000858   五粮液  1.64
..      ...    ...     ...   ...   ...
295  000300  沪深300  601698  中国卫通  0.04
296  000300  沪深300  300979  华利集团  0.04
297  000300  沪深300  000800  一汽解放  0.04
298  000300  沪深300  601236  红塔证券  0.04
299  000300  沪深300  001289  龙源电力  0.02

[300 rows x 5 columns]

In [65]:
data300 = ef.stock.get_members('000300')

In [66]:
data300.to_csv('list300')

In [67]:
import investpy

df = investpy.get_stock_historical_data(stock='AAPL',
                                        country='United States',
                                        from_date='01/01/2010',
                                        to_date='01/01/2020')
print(df.head())

ConnectionError: ERR#0015: error 403, try again later.

In [ ]:
ef.stock.get_members('000300')

In [68]:
ef.stock.get_base_info('603290')

股票代码                  603290
股票名称                    斯达半导
净利润             429938269.41
总市值       33606840176.799999
流通市值      33606840176.799999
所处行业                     半导体
市盈率(动)                 39.08
市净率                     5.67
ROE                     7.32
毛利率                36.181089
净利率                25.707829
板块编号                  BK1036
dtype: object

In [ ]:
import pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('cn_stock_list.xlsx')

/opt/homebrew/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [ ]:
df

       Code  Name Sector 2
0    300059  东方财富    互联网服务
1    600845  宝信软件    互联网服务
2    300496  中科创达    互联网服务
3       938  紫光股份    互联网服务
4    688187  时代电气     交运设备
..      ...   ...      ...
295  605499  东鹏饮料     食品佽料
296  603288  海天味业     食品佽料
297  300999   金龙鱼     食品饮料
298  600887  伊利股份     食品饮料
299     895  双汇发展     食品饮料

[300 rows x 3 columns]

In [ ]:
df['new sector'] = 'empty'

In [ ]:
df

       Code  Name Sector 2 new sector
0    300059  东方财富    互联网服务      empty
1    600845  宝信软件    互联网服务      empty
2    300496  中科创达    互联网服务      empty
3       938  紫光股份    互联网服务      empty
4    688187  时代电气     交运设备      empty
..      ...   ...      ...        ...
295  605499  东鹏饮料     食品佽料      empty
296  603288  海天味业     食品佽料      empty
297  300999   金龙鱼     食品饮料      empty
298  600887  伊利股份     食品饮料      empty
299     895  双汇发展     食品饮料      empty

[300 rows x 4 columns]

In [ ]:
df.loc[1]

Code          600845
Name            宝信软件
Sector 2       互联网服务
new sector     empty
Name: 1, dtype: object

In [74]:
for i in range(len(df)):
    info = ef.stock.get_base_info(str(df.loc[i,"Code"]).zfill(6))
    df.loc[i,"new sector"] = info["所处行业"]
    print(df.loc[i, "Name"], df.loc[i,'new sector'])

东方财富 互联网服务
宝信软件 互联网服务
中科创达 互联网服务
紫光股份 互联网服务
时代电气 交运设备
中国中车 交运设备
芒果超媒 文化传媒
分众传媒 文化传媒
中国人寿 保险
中国太保 保险
新华保险 保险
中国人保 保险
中国平安 保险
新奥股份 燃气
温氏股份 农牧饲渔
牧原股份 农牧饲渔
海大集团 农牧饲渔
新希望 农牧饲渔
华熙生物 美容护理
万泰生物 生物制品
药明康德 医疗服务
上海医药 医药商业
通策医疗 医疗服务
片仔癀 中药
白云山 中药
恒瑞医药 化学制药
复星医药 化学制药
同仁堂 中药
爱美客 美容护理
迈瑞医疗 医疗器械
康龙化成 医疗服务
康泰生物 生物制品
泰格医药 医疗服务
沃森生物 生物制品
智飞生物 生物制品
爱尔眼科 医疗服务
凯莱英 医疗服务
上海莱士 生物制品
华兰生物 生物制品
新和成 化学制药
华东医药 化学制药
长春高新 生物制品
云南白药 中药
中芯国际 半导体
华润微 半导体
韦尔股份 半导体
北方华创 半导体
中微公司 半导体
长电科技 半导体
中国中免 旅游酒店
中国重工 船舶制造
航发动力 航天航空
中航沈飞 航天航空
中国船舶 船舶制造
中航西飞 航天航空
凯赛生物 化学制品
君正集团 化学原料
华鲁恒升 化学原料
万华化学 化学制品
中国巨石 玻璃玻纤
贝泰妮 美容护理
卫星化学 化学原料
龙佰集团 化学原料
荣盛石化 化纤行业
华峰化学 化纤行业
盐湖股份 化肥行业
藏格矿业 化肥行业
东方盛虹 化纤行业
中油资本 多元金融
德业股份 家电行业
海尔智家 家电行业
三花智控 家电行业
格力电器 家电行业
美的集团 家电行业
中国能建 工程建设
中国交建 工程建设
中国电建 工程建设
中国建筑 工程建设
中国中冶 工程建设
中国中铁 工程建设
中国铁建 工程建设
中国化学 工程建设
四川路桥 工程建设
福莱特 玻璃玻纤
海螺水泥 水泥建材
东方雨虹 装修建材
天山股份 水泥建材
北新建材 装修建材
新城控股 房地产开发
绿地控股 房地产开发
金地集团 房地产开发
保利发展 房地产开发
招商蛇口 房地产开发
华侨城A 房地产开发
万科A 房地产开发
锦江酒店 旅游酒店
大全能源 光伏设备
容百科技 电池
洛阳钼业 小金属
华友钴业 能源金属
璞泰来 电池
合盛硅业 非金属材料
紫金矿业 贵金属
中国铝业 有色金属
杉杉股份 电子元件
山东黄金 贵金属
江西铜业 有色金属
南山铝业 有色金属
北方稀土 小金属
德方纳米 化学制品
亿纬锂能 电池
天赐材料 化学制品
天齐锂业 能源金属
赣锋锂业 能源金属
科沃斯 家电行业
弘元绿能 光伏设备
恒立液压 工程机械
三一重工 工程机械
先导智能 电池
汇川技术 电子元件
徐工机械 工程机械
中联重科 工程机械
长城汽车 汽车整车
广汽集团 汽车整车
上汽集团 汽车整车
比亚迪 汽车整车
一汽解放 汽车整车
长安汽车 汽车整车
星宇股份 汽车零部件
拓普集团 汽车零部件
华域汽车 汽车零部件
福耀玻璃 玻璃玻纤
德赛西威 汽车零部件
潍柴动力 汽车零部件
工业富联 消费电子
传音控股 消费电子
立讯精密 消费电子
歌尔股份 消费电子
三七互娱 游戏
京沪高铁 物流行业
大秦铁路 物流行业
圆通速递 物流行业
顺丰控股 物流行业
韵达股份 物流行业
中国核电 电力行业
三峡能源 电力行业
长江电力 电力行业
国投电力 电力行业
国电电力 电力行业
川投能源 电力行业
华能水电 电力行业
华能国际 电力行业
中国广核 电力行业
龙源电力 电力行业
沪硅产业 半导体
澜起科技 半导体
兆易创新 半导体
斯达半导 半导体
闻泰科技 消费电子
士兰微 半导体
生益科技 电子元件
中伟股份 电池
卓胜微 半导体
圣邦股份 半导体
蓝思科技 消费电子
三环集团 电子元件
北京君正 半导体
欣旺达 电池
鹏鼎控股 电子元件
深南电路 电子元件
视源股份 消费电子
高德红外 电子元件
纳思达 计算机设备
中航光电 电子元件
紫光国微 半导体
振华科技 电子元件
京东方A 光学光电子
TCL科技 光学光电子
天合光能 光伏设备
晶科能源 光伏设备
福斯特 光伏设备
正泰电器 电网设备
明阳智能 风电设备
隆基绿能 光伏设备
东方电气 电源设备
爱旭股份 光伏设备
通威股份 光伏设备
国电南瑞 电网设备
特变电工 电网设备
锦浪科技 光伏设备
迈为股份 专用设备
宁德时代 电池
晶盛机电 光伏设备
阳光电源 光伏设备
晶澳科技 光伏设备
金风科技 风电设备
TCL中环 光伏设备
国轩高科 电池
中煤能源 煤炭行业
中国石油 石油行业
中海油服 采掘行业
潞安环能 煤炭行业
陕西煤业 煤炭行业
中国神华 煤炭行业
宝丰能源 化学原料
恒力石化 化纤行业
兖矿能源 煤炭行业
中国石化 石油行业
山西焦煤 煤炭行业
美锦能源 煤炭行业
华利集团 纺织服装
中国国航 航空机场
春秋航空 航空机场
中国东航 航空机场
南方航空 航空机场
上海机场 航空机场
招商轮船 航运港口
中远海控 航运港口
上港集团 航运港口
海康威视 计算机设备
中科曙光 计算机设备
大华股份 计算机设备
浪潮信息 计算机设备
方正证券 证券
中国银河 证券
浙商证券 证券
光大证券 证券
华泰证券 证券
兴业证券 证券
红塔证券 证券
国泰君安 证券
招商证券 证券
东方证券 证券
中泰证券 证券
海通证券 证券
中信证券 证券
国信证券 证券
广发证券 证券
中金公司 证券
中信建投 证券
国投资本 证券
申万宏源 证券
同花顺 软件开发
金山办公 软件开发
三六零 软件开发
奇安信 软件开发
用友网络 软件开发
恒生电子 软件开发
深信服 软件开发
广联达 软件开发
科大讯飞 软件开发
晨光股份 家用轻工
欧派家居 装修建材
公牛集团 家电行业
恩捷股份 电池
中国电信 通信服务
中国移动 通信服务
中国联通 通信服务
中兴通讯 通信设备
中国卫通 通信服务
亿联网络 通信设备
今世缘 酿酒行业
山西汾酒 酿酒行业
青岛啤酒 酿酒行业
贵州茅台 酿酒行业
重庆啤酒 酿酒行业
洋河股份 酿酒行业
五粮液 酿酒行业
古井贡酒 酿酒行业
泸州老窖 酿酒行业
宝钢股份 钢铁行业
包钢股份 钢铁行业
永兴材料 钢铁行业
中信特钢 钢铁行业
中信银行 银行
中国银行 银行
建设银行 银行
成都银行 银行
光大银行 银行
邮储银行 银行
工商银行 银行
交通银行 银行
农业银行 银行
上海银行 银行
北京银行 银行
兴业银行 银行
南京银行 银行
杭州银行 银行
江苏银行 银行
招商银行 银行
民生银行 银行
华夏银行 银行
浦发银行 银行
宁波银行 银行
平安银行 银行
东鹏饮料 食品饮料
海天味业 食品饮料
金龙鱼 食品饮料
伊利股份 食品饮料
双汇发展 食品饮料

In [75]:
df

       Code  Name Sector 2 new sector
0    300059  东方财富    互联网服务      互联网服务
1    600845  宝信软件    互联网服务      互联网服务
2    300496  中科创达    互联网服务      互联网服务
3       938  紫光股份    互联网服务      互联网服务
4    688187  时代电气     交运设备       交运设备
..      ...   ...      ...        ...
295  605499  东鹏饮料     食品佽料       食品饮料
296  603288  海天味业     食品佽料       食品饮料
297  300999   金龙鱼     食品饮料       食品饮料
298  600887  伊利股份     食品饮料       食品饮料
299     895  双汇发展     食品饮料       食品饮料

[300 rows x 4 columns]

In [78]:
df.to_excel('new.xlsx',sheet_name='s1',index=False)

In [79]:
today_quote = ef.stock.get_realtime_quotes()

In [80]:
today_quote

,股票代码,股票名称,涨跌幅,最新价,最高,最低,今开,涨跌额,换手率,量比,动态市盈率,成交量,成交额,昨日收盘,总市值,流通市值,行情ID,市场类型,更新时间,最新交易日
0,831445,龙竹科技,29.77,4.97,4.97,3.91,3.91,1.14,3.67,10.85,101.11,33925,16217001.49,3.83,741255744,459508676,0.831445,深A,2023-09-04 13:57:47,2023-09-04
1,835174,五新隧装,27.22,14.16,14.46,13.0,13.0,3.03,12.60,5.96,8.83,65279,89818900.83,11.13,1274523447,733681072,0.835174,深A,2023-09-04 13:57:47,2023-09-04
2,836675,秉扬科技,24.89,5.72,5.88,4.95,5.3,1.14,8.40,30.47,13.05,65748,34842729.32,4.58,984972560,447844368,0.836675,深A,2023-09-04 13:57:47,2023-09-04
3,300045,华力创通,20.03,16.72,16.72,14.51,14.99,2.79,35.19,2.15,-452.06,1734186,2748674054.38,13.93,11079929946,8239965465,0.300045,深A,2023-09-04 13:57:48,2023-09-04
4,300749,顶固集创,20.0,11.28,11.28,9.6,9.6,1.88,22.38,7.7,54.33,347225,373641495.64,9.4,2321787216,1750234128,0.300749,深A,2023-09-04 13:57:48,2023-09-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5506,603879,永悦科技,-9.96,8.14,8.6,8.14,8.45,-0.9,5.68,2.26,-83.78,203976,167646260.0,9.04,2936276592,2925063742,1.603879,沪A,2023-09-04 13:57:50,2023-09-04
5507,000811,冰轮环境,-9.96,14.92,16.77,14.91,16.69,-1.65,4.11,4.63,14.98,306318,463506925.35,16.57,11127900036,11127673655,0.000811,深A,2023-09-04 13:57:48,2023-09-04
5508,600039,四川路桥,-10.02,7.99,8.3,7.99,8.21,-0.89,1.20,3.81,6.16,800033,642431057.0,8.88,69637469538,53047995215,1.600039,沪A,2023-09-04 13:57:50,2023-09-04
5509,301231,荣信文化,-11.01,34.93,38.09,34.56,38.0,-4.32,32.89,1.05,231.87,69406,250113645.64,39.25,2948092000,737023000,0.301231,深A,2023-09-04 13:57:48,2023-09-04
5510,688365,光云科技,-11.18,11.2,12.74,11.2,12.48,-1.41,4.21,3.33,-53.48,179437,212979722.0,12.61,4769236461,4769236461,1.688365,沪A,2023-09-04 13:57:49,2023-09-04